name = "lulema"
compatibility_date = "2025-01-18"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NODE_ENV = "production"

# Supabase Configuration
SUPABASE_URL = "https://owdbswjdybicrbdvvrkj.supabase.co"
SUPABASE_ANON_KEY = "sb_publishable_5QswQz8Q6r4LmApO7GqwQg_mwGiBkLi"
